### ISSUE TITLE
User sees ‘recipe of the day’

### ISSUE THREAD

**Issue by eniolajohnson** [eniolajohnson/perfect-pepper#1]
## 💰 Motivation

A good recipe app should be able to offer me something nice I can try out without searching for it.

## ✅ Task List

- [ ]  Create the home page
- [ ]  Send a get request to the API, to get a random recipe every 24 hours
- [ ]  Add the navigation bar on the home page
- [ ]  Create the recipe page when user clicks  on the recipe title.
